### PR TITLE
feat: allow setting `font` to `none`

### PR DESCRIPTION
**Pull request by RubixDev**
When set to `none`, the default monospace font which is used for `raw` code blocks will be used. The default is left as `Cascadia Code` so that this is not a breaking change.

demo</img>

```typ
#import "../ansi-render.typ": *

#set page(width: auto, height: auto, margin: 10pt)

#let demo-text = "\u{1b}[38;2;255;0;0mThis text is red.\u{1b}[0m
\u{1b}[48;2;0;255;0mThis background is green.\u{1b}[0m
\u{1b}[38;2;255;255;255m\u{1b}[48;2;0;0;255mThis text is white on a blue background.\u{1b}[0m
\u{1b}[1mThis text is bold.\u{1b}[0m
\u{1b}[4mThis text is underlined.\u{1b}[0m
\u{1b}[38;2;255;165;0m\u{1b}[48;2;255;255;0mThis text is orange on a yellow background.\u{1b}[0m
"

#ansi-render(
  demo-text,
  inset: 5pt,
  radius: 3pt,
  theme: terminal-themes.vscode,
  font: "invalid font",
)
#ansi-render(
  demo-text,
  inset: 5pt,
  radius: 3pt,
  theme: terminal-themes.vscode,
  font: none,
)
#ansi-render(
  demo-text,
  inset: 5pt,
  radius: 3pt,
  theme: terminal-themes.vscode,
  font: "JetBrains Mono",
)
```

### CODE REVIEW

**Comment by 8LWXpg** [comment]
I changed its behavior to fall back on a specific font on `none` because there's an issue with using `raw(str)` on rendering empty newlines (not sure if it's a bug with typst) and the default font in `raw` [#2231](https://github.com/typst/typst/issues/2231).

However, I do like the Idea of using same setting as `raw` has, so feel free to make another PR if you have a solution.

**Comment by RubixDev** [comment]
I know there are issues with the default font (I also noticed the ascender being wrong, and the font has been unmaintained for six years), but I thought it would still be the best fit for `none` given it's the only monospace font that comes bundled with the typst binary. Users can of course always set the font to `DejaVu Sans Mono` themselves, but that requires them to know what the default font is, and that also might change with future typst versions.

As for the newline problem, you're right there seems to be something fishy going on. `raw("a\nb")` works as expected, but `raw("a");raw("\n");raw("b")` stays on one line, and `raw("a");raw("\n\n");raw("b")` only inserts one newline. I guess we could split the string by newlines and use `linebreak()` for every `\n` instead :shrug:

**Comment by 8LWXpg** [comment]
I changed to `raw` in latest commit and probably fixed the issue. 

image

**Comment by RubixDev** [comment]
Okay so you manually do the line breaks now and always use `raw`, but looks good. Thanks!

**Comment by RubixDev** [comment]
I still opened an issue on Typst https://github.com/typst/typst/issues/2240 because the behavior is inconsistent between using `text("\n")` and `raw("\n")`

**Pull request merged**
